ALTER TABLE funcionarios ALTER COLUMN nome DROP NOT NULL;
ALTER TABLE funcionarios ALTER COLUMN cpf DROP NOT NULL;
ALTER TABLE funcionarios ALTER COLUMN telefone DROP NOT NULL;
ALTER TABLE funcionarios ALTER COLUMN email DROP NOT NULL;